### ISSUE TITLE
Custom element doesn't exist: surveillance-card

### ISSUE THREAD

**Issue by dominikheinz** [custom-cards/surveillance-card#15] opened 2019-05-10 09:28 UTC
I've added the `surveillance-card.js` file in the folder where all the other home assistant yaml files are stored. Since the `ui-lovelace.yaml` file didn't exist previously I've created it and add custom card info:

```
resources:
  - url: surveillance-card.js
    type: module
```
I added the card to the UI and I am prompted this:
```
Custom element doesn't exist: surveillance-card.

{
  "type": "custom:surveillance-card",
  "thumb_interval": 15,
  "update_interval": 2,
  "cameras": [
    {
      "entity": "camera.my_camera"
    }
  ]
}
```

What did I misconfigurate that it can't find the custom element?

**Comment by grv2k8** [comment] 2019-06-14 05:08
I have the same issue with this card. Did you manage to get it resolved?

**Comment by kaskader13** [comment] 2019-07-10 14:36
I have the same issue with this card. Did you manage to get it resolved?

**Comment by manny199** [comment] 2019-07-10 15:36
I have a problem, I switch in yaml mode and insert the lines into file ui-lovelace.yaml but in lovelace UI I obtain only one card.
How can integrate this card and other cards togheter in lovelace ui without use yaml mode?

**Comment by prasket** [comment] 2019-08-09 00:55
this is a duplicate of: https://github.com/custom-cards/surveillance-card/issues/10

**Closed** 2020-05-19 23:14 UTC
