### ISSUE TITLE
TypeError: this._hass.states[currentCamera] is undefined

### ISSUE THREAD

**Issue by codeclinic** [custom-cards/surveillance-card#16] opened 2019-08-07 12:16 UTC
The camera isnt loading (just a black card) and this is showing in my log:

TypeError: this._hass.states[currentCamera] is undefined

I have the following in raw config editor:

`  - badges: []
    cards:
      - cameras:
          - entity: camera.mobile_demo
        thumb_interval: 15
        type: 'custom:surveillance-card'
        update_interval: 2
    icon: 'mdi:security'
    title: Security`

**Comment by niemyjski** [comment] 2020-05-26 21:46
This is a duplicate of #14

**Closed by niemyjski** 2020-05-26 21:46 UTC
Labels: bug, help wanted

**Comment by niemyjski** [comment] 2020-05-26 23:16
I also committed a safety fix for this but it can be caused by invalid camera configuration.
